version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: short-url-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: short_url
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql # 데이터 영구 저장